version: '3.8'

services:

  reserva-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    env_file:
      - .env
    depends_on:
        - postgres_db
    links:
        - postgres_db

  postgres_db:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"